portal/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout_then_login


app_name = 'portal'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    # url(r'^portal_login/$', views.portal_login, name='portal_login'),
    url(r'^campaigns/$', views.campaigns, name='campaigns'),
    url(r'^get_prospect/(?P<campaign_id>[0-9]+)/$', views.get_prospect, name='get_prospect'),
    # url(r'^updated_prospect/(?P<prospect_id>[0-9]+)')
    url(r'^campaign/(?P<campaign_id>[0-9]+)/$', views.campaign_details, name='campaign_details'),
    url(r'^make_lead/(?P<campaign_id>[0-9]+)/(?P<prospect_id>[0-9]+)/$', views.make_lead, name='make_lead'),
    url(r'^make_dnc/(?P<campaign_id>[0-9]+)/(?P<prospect_id>[0-9]+)/$', views.make_dnc, name='make_dnc'),
    url(r'^make_view/(?P<campaign_id>[0-9]+)/(?P<prospect_id>[0-9]+)/$', views.make_view, name='make_view'),
    url(r'^make_changes/(?P<campaign_id>[0-9]+)/(?P<prospect_id>[0-9]+)/$', views.make_changes, name='make_changes'),
    url(r'^my_leads/(?P<campaign_id>[0-9]+)/$', views.my_leads, name='my_leads'),
    url(r'^my_views/(?P<campaign_id>[0-9]+)/$', views.my_views, name='my_views'),
    url(r'^my_dncs/(?P<campaign_id>[0-9]+)/$', views.my_dncs, name='my_dncs'),
    url(r'^login/$', login, {'template_name': 'portal/portal_login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),

]

portal/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save


class Campaign(models.Model):
    Name = models.CharField(max_length=200)
    Start_Date = models.DateField(blank=True, null=True)
    Status = models.BooleanField(default=False)
    End_Date = models.DateField(blank=True, null=True)
    Users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    def __str__(self):
        return self.Name


class Prospect(models.Model):
    Name            = models.CharField(max_length=200)
    Phone           = models.CharField(max_length=200, blank=True, null=True, default='-')
    Email           = models.CharField(max_length=200, blank=True, null=True, default='-')
    Job_Title       = models.CharField(max_length=200, blank=True, null=True, default='-')
    Industry_Type   = models.CharField(max_length=200, blank=True, null=True, default='-')
    Company         = models.CharField(max_length=200, blank=True, null=True, default='-')
    Website         = models.CharField(max_length=200, blank=True, null=True, default='-')
    Emp_Size        = models.CharField(max_length=200, blank=True, null=True, default='-')
    City            = models.CharField(max_length=200, blank=True, null=True, default='-')
    Country         = models.CharField(max_length=200, blank=True, null=True, default='-')
    State           = models.CharField(max_length=200, blank=True, null=True, default='-')
    Zip_Code        = models.CharField(max_length=200, blank=True, null=True, default='-')
    Direct_Or_Extension     = models.CharField(max_length=200, blank=True, null=True, default='-')
    Campaigns       = models.ManyToManyField(Campaign, blank=True)
    Lead_Count      = models.IntegerField(default=0)
    View_Count      = models.IntegerField(default=0)
    Released_Campaigns      = models.CharField(max_length=1000, default='-')
    Info_Updated_User       = models.CharField(max_length=200, blank=True, null=True, default='-')
    Info_Updated_Campaign   = models.CharField(max_length=200, blank=True, null=True, default='-')
    Notes           = models.TextField(blank=True, null=True, default='')
    To_Be_Updated   = models.BooleanField(default=False)
    Update_Phone    = models.CharField(max_length=200, blank=True, null=True, default='-')
    Update_Email    = models.CharField(max_length=200, blank=True, null=True, default='-')
    Update_Company  = models.CharField(max_length=200, blank=True, null=True, default='-')
    Old_Info        = models.TextField(blank=True, null=True, default='-')

    def __str__(self):
        return self.Name

    def info_update(self, **kwargs):
        for field, value in kwargs.items():
            self.field = value
            self.save()
        self.save()


# def emp_size_setter(sender, instance, *args,**kwargs):
#     emp_stanadrd = [(1, 10), (11, 50), (51, 200), (201, 500),
#                     (501, 1000), (1001, 5000), (5001, 10000), (10001, 99999)]
#     emp_class = ['1to1', '11to50', '51to200', '201to500',
#                  '501to2000', '1001to5000', '5001to10000', '10000+']
#     try:
#         instance.emp_size
#     except:
#
#     try:
#         for rng in emp_stanadrd:
#             if
#
# post_save.connect(emp_size_setter, sender=Prospect)


class Lead(models.Model):
    Lead_On = models.DateField(blank=True, null=True)
    Prospect = models.ForeignKey(Prospect, on_delete=models.CASCADE)
    Campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    Lead_User = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.Prospect.Name


class View(models.Model):
    Viewed_On = models.DateField(blank=True, null=True)
    Prospect = models.ForeignKey(Prospect, on_delete=models.CASCADE)
    Campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    View_User = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.Prospect.Name


class DNC(models.Model):
    DNC_On = models.DateField(blank=True, null=True)
    Prospect = models.ForeignKey(Prospect, on_delete=models.CASCADE)
    Campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    DNC_User = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.Prospect.Name




portal/templates/portal/assign_campaign.html
{% extends "admin/base_site.html" %}

{% block content %}
<form action="" method="post">  
  {% csrf_token %}
<p>  
Are you sure you want to assign following prospects to campaign?
</p>
  {% for prospect in prospects %}
    <p>
      {{ prospect }}
    </p>
    <input type="hidden" name="_selected_action" value="{{ prospect.pk }}" />
  {% endfor %}

  <input type="hidden" name="action" value="assign_campaign" />
    <h4>Please select a Campaign from Dropdown </h4>

    <select name="campaign_id">
        {% for campaign in campaigns %}
                    <option value={{ campaign.id }}>{{ campaign.Name }}</option>
        {% endfor %}
    </select>
  <input type="submit" name="assign" value="Assign"/>
</form>  
{% endblock %}

portal/templates/portal/campaign_details.html
{% extends 'base.html' %}

{% block title  %}
    <title>{{campaign.Name}} | Fine-Leap Systems</title>
{% endblock %}

{% block content %}
    <br>

    <div class="jumbotron container text-center">

        <div class="container">

            <a href="{% url 'portal:campaigns' %}" style="float: left"><h3 class="fa fa-arrow-left"></h3></a>
            <h2>{{campaign.Name}}</h2>
            <hr>
        <div class="row">
            <span style="float: left"><b><i class="fa fa-user"> </i>  {{user.username}}</b></span>
            <a href={% url 'portal:my_views' campaign_id=campaign.id %} style="float:right;">
            <button class="btn "><b><i class="fa fa-check-square"></i> My Views <span class="aa-number-circle">{{user.view_set.count}}</span></b></button>
            </a>
            <a href={% url 'portal:my_leads' campaign_id=campaign.id %} style='margin-right:30px;float:right;' >
            <button class="btn"><b><i class="fa fa-hand-o-up"></i> My Leads <span class="aa-number-circle">{{user.lead_set.count}}</span></b></button>
            </a>
            <a href={% url 'portal:my_dncs' campaign_id=campaign.id %} style='margin-right:30px;float:right;' >
            <button class="btn"><b>My DNCS <span class="aa-number-circle">{{user.dnc_set.count}}</span></b></button>
            </a>
            <br><br>
        </div>
        <table class="table table-bordered">
            <tr><td>Name</td><td>{{campaign.Name}}</td></tr>
            <tr><td>Start From</td><td>{{campaign.Start_Date}}</td></tr>
            <tr><td>End To</td><td>{{campaign.End_Date}}</td></tr>
            <tr><td>Status</td><td>{{campaign.Status}}</td></tr>
        </table>
            <a href={% url 'portal:get_prospect' campaign_id=campaign.id%}><button class="btn"><b>Get Prospect</b></button></a>

        </div>

    </div>


{% endblock %}




portal/templates/portal/campaigns.html
{% extends 'base.html' %}

{% block title  %}
    <title>Campaigns | Fine-Leap Systems</title>
{% endblock %}



{% block content %}

    <br>

    <div class="jumbotron container text-center">

        <a href="{% url 'portal:home' %}" style="float: left"><h3 class="fa fa-arrow-left"></h3></a>

        <h2> <i class="fa fa-list-alt"></i> Active Campaigns</h2>
        <br>
        {% for campaign in campaigns %}
        <a href={% url 'portal:campaign_details' campaign_id=campaign.id %}><button class="btn " style="margin: 10px;"><b>{{ campaign.Name }}</b></button></a>
        {% endfor %}
    </div>

{% endblock %}


portal/templates/portal/home.html
{% extends 'base.html' %}
{% block title %}<title>Home | Fine-Leap Systems</title>{% endblock %}

portal/templates/portal/my_dncs.html
{% extends 'base.html' %}

{% block title  %}
    <title>My DNCS | {{dncs.first.DNC_User.username}}</title>
{% endblock %}

{% block content %}
    <br>

    <div style="padding:40px;" class="jumbotron container text-center">

        <a href="{% url 'portal:campaign_details' campaign_id=campaign_id %}" style="float: left"><h3 class="fa fa-arrow-left"></h3></a>

        <h2> All DNCS : {{dncs.count}}</h2>
        <h4 style="float: right"><i class="fa fa-user"> </i> : {{dncs.first.DNC_User.username}}</h4>
        <table class="table table-bordered ">
            <tr>
                <td>Sr No.</td>
                <td>Name</td>
                <td>Date</td>
            </tr>
            {% for dnc in dncs %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{dnc.Prospect.Name}}</td>
                    <td>{{dnc.DNC_On}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}




portal/templates/portal/my_leads.html
{% extends 'base.html' %}

{% block title  %}
    <title>My Leads | {{leads.first.Lead_User.username}}</title>
{% endblock %}

{% block content %}
    <br>

    <div style="padding:40px;" class="jumbotron container text-center">

        <a href="{% url 'portal:campaign_details' campaign_id=campaign_id %}" style="float: left"><h3 class="fa fa-arrow-left"></h3></a>

        <h2> All Leads : {{leads.count }}</h2>
        <h4 style="float: right"><i class="fa fa-user"> </i> : {{leads.first.Lead_User.username}}</h4>
        <table class="table table-bordered ">
            <tr>
                <td>Sr No.</td>
                <td>Name</td>
                <td>Date</td>
            </tr>
            {% for lead in leads %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{lead.Prospect.Name}}</td>
                    <td>{{lead.Lead_On}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}




portal/templates/portal/my_views.html
{% extends 'base.html' %}

{% block title  %}
    <title>My Views | {{views.first.View_User.username}}</title>
{% endblock %}

{% block content %}
    <br>

    <div style="padding:40px;" class="jumbotron container text-center">

        <a href="{% url 'portal:campaign_details' campaign_id=campaign_id %}" style="float: left"><h3 class="fa fa-arrow-left"></h3></a>

        <h2> All Views : {{views.count }}</h2>
        <h4 style="float: right"><i class="fa fa-user"> </i> : {{views.first.View_User.username}}</h4>
        <table class="table table-bordered ">
            <tr>
                <td>Sr No.</td>
                <td>Name</td>
                <td>Date</td>
            </tr>
            {% for view in views %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{view.Prospect.Name}}</td>
                    <td>{{view.Viewed_On}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}


portal/templates/portal/portal_login.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}">
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<p class="errornote">
{% blocktrans trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to login to a different account?
{% endblocktrans %}
</p>
{% endif %}

<form  method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
        <label class="required" for="id_username">Username:</label>
        <input type="text" name="username" autofocus="" required="" id="id_username">
  </div>
  <div class="form-row">
        <label class="required" for="id_password">Password:</label>
        <input type="password" name="password" required="" id="id_password">
  </div>
  <div class="submit-row">
        <input type="submit" value="{% trans 'Log in' %}">
  </div>
</form>

</div>
{% endblock %}

portal/templates/portal/single_prospect.html

{% extends 'base.html' %}

{% block title  %}
    <title>{{prospect.Name.title}} | Fine-Leap Systems</title>
{% endblock %}

{% block content %}
    <br>

    <div class="jumbotron container text-center" style="padding: 30px">

        {% if prospect %}
            <a href="{% url 'portal:campaign_details' campaign_id=campaign.id %}" style="float: left"><h3 class="fa fa-arrow-left"></h3></a>
        {% endif %}

        {% if empty_msg %}
        <a href="{% url 'portal:campaigns' %}" style="float: left"><h3 class="fa fa-arrow-left"></h3></a>
        <h3>{{ empty_msg }}</h3>{% endif %}
        {% if prospect %}
            <h2><i class="far fa-address-card"></i> {{prospect.Name.upper}}</h2>
            <table class="table table-bordered table-striped" style="font-weight: bold">
                <tr><td>Name</td><td>{{prospect.Name}}</td></tr>
                <tr><td><i class="fas fa-phone-volume"></i> Phone</td><td><input type="text" value="{{prospect.Phone}}" id="myInput">  <button class="btn " onclick="myFunction()">Copy text</button></td></tr>
                <tr><td>Industry Type</td><td>{{prospect.Industry_Type}}</td></tr>
                <tr><td>Job Title</td><td>{{prospect.Job_Title}}</td></tr>
                <tr><td> <i class="fa fa-mail"></i> Email</td><td>{{prospect.Email}}</td></tr>
                <tr><td> <i class="fa fa-globe"></i> Website</td><td>{{prospect.Website}}</td></tr>
                <tr><td> <i class="fa fa-users"></i> Emp Size</td><td>{{prospect.Emp_Size}}</td></tr>
                <tr><td>Company</td><td>{{prospect.Company}}</td></tr>
                <tr><td> <i class="fas fa-city"></i> City</td><td>{{prospect.City}}</td></tr>

            </table>

            {# <!--<a href={% url 'portal:make_lead' campaign_id=campaign.id prospect_id=prospect.id %} ><button type="submit" class="btn" style="margin: 10px"><b>Make Lead</b></button></a>-->#}
            {# <!--<a href={% url 'portal:make_view' campaign_id=campaign.id prospect_id=prospect.id %} ><button type="submit" class="btn" style="margin: 10px"><b>Make View</b></button></a>-->#}
             {#<!--<a href={% url 'portal:make_dnc' campaign_id=campaign.id prospect_id=prospect.id %} ><button type="submit" class="btn" style="margin: 10px"><b>Make DNC</b></button></a>-->#}

                <a href={% url 'portal:make_lead' campaign_id=campaign.id prospect_id=prospect.id %} ><input type="submit" class="btn" style="margin: 10px;font-weight: bold" value="Make Lead"></a>
                <a href={% url 'portal:make_view' campaign_id=campaign.id prospect_id=prospect.id %} ><input type="submit" class="btn" style="margin: 10px;font-weight: bold" value="Make View"></a>
                <a href={% url 'portal:make_dnc' campaign_id=campaign.id prospect_id=prospect.id %} ><input type="submit" class="btn" style="margin: 10px;font-weight: bold" value="Make DNC"></a>




            <br><br>
            <hr>
            {% if form %}
                <form method="post" action={% url 'portal:make_changes' campaign_id=campaign.id prospect_id=prospect.id %}>
                    {% csrf_token %}
                    <b>Phone &nbsp; &nbsp; &nbsp;:</b><input class="aa-edit-form" type="text" name="phone">
                    <b>Email :</b><input class="aa-edit-form" type="text" name="email">
                    <br>
                    <b>Company :</b><input class="aa-edit-form" type="text" name="company">
                    <b>Notes :</b><input class="aa-edit-form" type="text" name="notes">
                    <br>
                    <input value="Save Changes" type="submit" class="btn" style="width: 35%;font-weight: bold">
                    <br>
                </form>
            {% endif %}

        {% endif %}
    </div>



    <script>
    function myFunction() {
        var copyText = document.getElementById("myInput");
        copyText.select();
        document.execCommand("copy");
        }
    </script>





{% endblock %}


portal/templates/portal/temp.html

{% extends 'base.html' %}

{% block title  %}
    <title>prospect.Name</title>
{% endblock %}

{% block my_content %}
    <br>

    <div class="jumbotron container text-center">
        {% if empty_msg %}<h2>{{ empty_msg }}</h2>{% endif %}
        {% if prospect %}
            <h2>{{prospect.Name}}</h2>
            <table class="table table-bordered">
                <tr><td>Name</td><td>{{prospect.Name}}</td></tr>
                <tr><td>Phone</td><td>{{prospect.Phone}}</td></tr>
                <tr><td>Industry Type</td><td>{{prospect.Industry_Type}}</td></tr>
                <tr><td>Job Title</td><td>{{prospect.Job_Title}}</td></tr>
            </table>

            <a href={% url 'make_lead' campaign_id=campaign.id prospect_id=prospect.id %} ><button class="btn">Make Lead</button></a>
            <a href={% url 'make_view' campaign_id=campaign.id prospect_id=prospect.id %} ><button class="btn">Make View</button></a>
            <a href={% url 'make_dnc' campaign_id=campaign.id prospect_id=prospect.id %} ><button class="btn">Make DNC</button></a>
        {% endif %}
    </div>

{% endblock %}


portal/templates/portal/test.html
<!--{% extends "admin/base_site.html" %}-->
<!--{% load i18n static %}-->

<!--{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}">-->
<!--{{ form.media }}-->
<!--{% endblock %}-->

<!--{% block bodyclass %}{{ block.super }} login{% endblock %}-->

<!--{% block usertools %}{% endblock %}-->

<!--{% block nav-global %}{% endblock %}-->

<!--{% block content_title %}{% endblock %}-->

<!--{% block breadcrumbs %}{% endblock %}-->

<!--{% block content %}-->
<!--{% if form.errors and not form.non_field_errors %}-->
<!--<p class="errornote">-->
<!--{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}-->
<!--</p>-->
<!--{% endif %}-->

<!--{% if form.non_field_errors %}-->
<!--{% for error in form.non_field_errors %}-->
<!--<p class="errornote">-->
    <!--{{ error }}-->
<!--</p>-->
<!--{% endfor %}-->
<!--{% endif %}-->

<!--<div id="content-main">-->

<!--{% if user.is_authenticated %}-->
<!--<p class="errornote">-->
<!--{% blocktrans trimmed %}-->
    <!--You are authenticated as {{ username }}, but are not authorized to-->
    <!--access this page. Would you like to login to a different account?-->
<!--{% endblocktrans %}-->
<!--</p>-->
<!--{% endif %}-->

<!--<form  method="post" id="login-form">{% csrf_token %}-->
  <!--<div class="form-row">-->
        <!--<label class="required" for="id_username">Username:</label>-->
        <!--<input type="text" name="username" autofocus="" required="" id="id_username">-->
  <!--</div>-->
  <!--<div class="form-row">-->
        <!--<label class="required" for="id_password">Password:</label>-->
        <!--<input type="password" name="password" required="" id="id_password">-->
  <!--</div>-->
  <!--<div class="submit-row">-->
        <!--<input type="submit" value="{% trans 'Log in' %}">-->
  <!--</div>-->
<!--</form>-->

<!--</div>-->
<!--{% endblock %}-->